apiVersion: v1
data:
  locustfile.py: |+
    from locust import HttpLocust, TaskSet


    def index(l):
        l.client.get("/")


    class UserBehavior(TaskSet):
        tasks = {index: 1}

    class WebsiteUser(HttpLocust):
        task_set = UserBehavior
        min_wait = 5000
        max_wait = 15000

kind: ConfigMap
metadata:
  name: kubelocust-config
